### ISSUE TITLE
Books (with details) for a given Series Id

### ISSUE THREAD

**Issue by GaProgMan** [GaProgMan/dwCheckApi#9]
Create an action in the Books controller which takes in a series Id and returns all of the books for that series, ordered by ordinal.

Method signature:

    public JsonResult GetForSeries(int seriesId)

Could either return the standard book view model, or a stripped down version (as the UI will only need the cover image and description - users will be able to click a link to navigate to the book profile page)

**Comment by GaProgMan** [comment]
Book Base View model needs only two properies:

- `bookCoverImageUrl`: a string - representing the url of the cover art
- `bookDescription`: a string - representing the synopsis of the book

**Comment by hatalaef** [comment]
I'll work on this.
